// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_tracker_to_ai.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* BallTracker_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BallTracker_reflection_ = NULL;
const ::google::protobuf::Descriptor* RobotTracker_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RobotTracker_reflection_ = NULL;
const ::google::protobuf::Descriptor* TrackerToAI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TrackerToAI_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  BallTracker_descriptor_ = file->message_type(0);
  BallTracker::default_instance_ = new BallTracker();
  static const int BallTracker_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallTracker, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallTracker, y_),
  };
  BallTracker_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BallTracker_descriptor_,
      BallTracker::default_instance_,
      BallTracker_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallTracker, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallTracker, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(BallTracker));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BallTracker_descriptor_, BallTracker::default_instance_);
  RobotTracker_descriptor_ = file->message_type(1);
  RobotTracker::default_instance_ = new RobotTracker();
  static const int RobotTracker_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotTracker, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotTracker, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotTracker, theta_),
  };
  RobotTracker_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RobotTracker_descriptor_,
      RobotTracker::default_instance_,
      RobotTracker_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotTracker, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotTracker, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(RobotTracker));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RobotTracker_descriptor_, RobotTracker::default_instance_);
  TrackerToAI_descriptor_ = file->message_type(2);
  TrackerToAI::default_instance_ = new TrackerToAI();
  static const int TrackerToAI_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrackerToAI, ball_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrackerToAI, robots_blue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrackerToAI, robots_yellow_),
  };
  TrackerToAI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TrackerToAI_descriptor_,
      TrackerToAI::default_instance_,
      TrackerToAI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrackerToAI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TrackerToAI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(TrackerToAI));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TrackerToAI_descriptor_, TrackerToAI::default_instance_);
  BallTracker::default_instance_->InitAsDefaultInstance();
  RobotTracker::default_instance_->InitAsDefaultInstance();
  TrackerToAI::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\033message_tracker_to_ai.proto\"#\n\013BallTra"
    "cker\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\"3\n\014RobotTrack"
    "er\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\022\r\n\005theta\030\003 \002(\001\""
    "s\n\013TrackerToAI\022\032\n\004ball\030\001 \002(\0132\014.BallTrack"
    "er\022\"\n\013robots_blue\030\002 \003(\0132\r.RobotTracker\022$"
    "\n\rrobots_yellow\030\003 \003(\0132\r.RobotTracker", 236,
  &protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5ftracker_5fto_5fai_2eproto {
  StaticDescriptorInitializer_message_5ftracker_5fto_5fai_2eproto() {
    protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  }
} static_descriptor_initializer_message_5ftracker_5fto_5fai_2eproto_;


// ===================================================================



BallTracker::BallTracker()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void BallTracker::InitAsDefaultInstance() {}

BallTracker::BallTracker(const BallTracker& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

BallTracker::~BallTracker() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* BallTracker::descriptor() {
  if (BallTracker_descriptor_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return BallTracker_descriptor_;
}

const BallTracker& BallTracker::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return *default_instance_;
}

BallTracker* BallTracker::default_instance_ = NULL;

BallTracker* BallTracker::New() const {
  return new BallTracker;
}

const ::google::protobuf::Descriptor* BallTracker::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* BallTracker::GetReflection() const {
  if (BallTracker_reflection_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return BallTracker_reflection_;
}

// ===================================================================




RobotTracker::RobotTracker()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u),
    theta_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void RobotTracker::InitAsDefaultInstance() {}

RobotTracker::RobotTracker(const RobotTracker& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u),
    theta_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

RobotTracker::~RobotTracker() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* RobotTracker::descriptor() {
  if (RobotTracker_descriptor_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return RobotTracker_descriptor_;
}

const RobotTracker& RobotTracker::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return *default_instance_;
}

RobotTracker* RobotTracker::default_instance_ = NULL;

RobotTracker* RobotTracker::New() const {
  return new RobotTracker;
}

const ::google::protobuf::Descriptor* RobotTracker::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* RobotTracker::GetReflection() const {
  if (RobotTracker_reflection_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return RobotTracker_reflection_;
}

// ===================================================================




TrackerToAI::TrackerToAI()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    ball_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void TrackerToAI::InitAsDefaultInstance() {  ball_ = const_cast< ::BallTracker*>(&::BallTracker::default_instance());
}

TrackerToAI::TrackerToAI(const TrackerToAI& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    ball_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

TrackerToAI::~TrackerToAI() {
  if (this != default_instance_) {
    delete ball_;
  }
}

const ::google::protobuf::Descriptor* TrackerToAI::descriptor() {
  if (TrackerToAI_descriptor_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return TrackerToAI_descriptor_;
}

const TrackerToAI& TrackerToAI::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return *default_instance_;
}

TrackerToAI* TrackerToAI::default_instance_ = NULL;

TrackerToAI* TrackerToAI::New() const {
  return new TrackerToAI;
}

const ::google::protobuf::Descriptor* TrackerToAI::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* TrackerToAI::GetReflection() const {
  if (TrackerToAI_reflection_ == NULL) protobuf_BuildDesc_message_5ftracker_5fto_5fai_2eproto();
  return TrackerToAI_reflection_;
}
