// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_sim_to_tracker.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* BallSim_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BallSim_reflection_ = NULL;
const ::google::protobuf::Descriptor* RobotSim_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RobotSim_reflection_ = NULL;
const ::google::protobuf::Descriptor* SimToTracker_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SimToTracker_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  BallSim_descriptor_ = file->message_type(0);
  BallSim::default_instance_ = new BallSim();
  static const int BallSim_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallSim, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallSim, y_),
  };
  BallSim_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BallSim_descriptor_,
      BallSim::default_instance_,
      BallSim_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallSim, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BallSim, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(BallSim));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BallSim_descriptor_, BallSim::default_instance_);
  RobotSim_descriptor_ = file->message_type(1);
  RobotSim::default_instance_ = new RobotSim();
  static const int RobotSim_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotSim, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotSim, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotSim, theta_),
  };
  RobotSim_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RobotSim_descriptor_,
      RobotSim::default_instance_,
      RobotSim_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotSim, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotSim, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(RobotSim));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RobotSim_descriptor_, RobotSim::default_instance_);
  SimToTracker_descriptor_ = file->message_type(2);
  SimToTracker::default_instance_ = new SimToTracker();
  static const int SimToTracker_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimToTracker, ball_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimToTracker, robots_blue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimToTracker, robots_yellow_),
  };
  SimToTracker_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SimToTracker_descriptor_,
      SimToTracker::default_instance_,
      SimToTracker_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimToTracker, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimToTracker, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(SimToTracker));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SimToTracker_descriptor_, SimToTracker::default_instance_);
  BallSim::default_instance_->InitAsDefaultInstance();
  RobotSim::default_instance_->InitAsDefaultInstance();
  SimToTracker::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\034message_sim_to_tracker.proto\"\037\n\007BallSi"
    "m\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\"/\n\010RobotSim\022\t\n\001x"
    "\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\022\r\n\005theta\030\003 \002(\001\"h\n\014SimT"
    "oTracker\022\026\n\004ball\030\001 \002(\0132\010.BallSim\022\036\n\013robo"
    "ts_blue\030\002 \003(\0132\t.RobotSim\022 \n\rrobots_yello"
    "w\030\003 \003(\0132\t.RobotSim", 218,
  &protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fsim_5fto_5ftracker_2eproto {
  StaticDescriptorInitializer_message_5fsim_5fto_5ftracker_2eproto() {
    protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  }
} static_descriptor_initializer_message_5fsim_5fto_5ftracker_2eproto_;


// ===================================================================



BallSim::BallSim()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void BallSim::InitAsDefaultInstance() {}

BallSim::BallSim(const BallSim& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

BallSim::~BallSim() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* BallSim::descriptor() {
  if (BallSim_descriptor_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return BallSim_descriptor_;
}

const BallSim& BallSim::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return *default_instance_;
}

BallSim* BallSim::default_instance_ = NULL;

BallSim* BallSim::New() const {
  return new BallSim;
}

const ::google::protobuf::Descriptor* BallSim::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* BallSim::GetReflection() const {
  if (BallSim_reflection_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return BallSim_reflection_;
}

// ===================================================================




RobotSim::RobotSim()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u),
    theta_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void RobotSim::InitAsDefaultInstance() {}

RobotSim::RobotSim(const RobotSim& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0u),
    y_(0u),
    theta_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

RobotSim::~RobotSim() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* RobotSim::descriptor() {
  if (RobotSim_descriptor_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return RobotSim_descriptor_;
}

const RobotSim& RobotSim::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return *default_instance_;
}

RobotSim* RobotSim::default_instance_ = NULL;

RobotSim* RobotSim::New() const {
  return new RobotSim;
}

const ::google::protobuf::Descriptor* RobotSim::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* RobotSim::GetReflection() const {
  if (RobotSim_reflection_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return RobotSim_reflection_;
}

// ===================================================================




SimToTracker::SimToTracker()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    ball_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void SimToTracker::InitAsDefaultInstance() {  ball_ = const_cast< ::BallSim*>(&::BallSim::default_instance());
}

SimToTracker::SimToTracker(const SimToTracker& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    ball_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

SimToTracker::~SimToTracker() {
  if (this != default_instance_) {
    delete ball_;
  }
}

const ::google::protobuf::Descriptor* SimToTracker::descriptor() {
  if (SimToTracker_descriptor_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return SimToTracker_descriptor_;
}

const SimToTracker& SimToTracker::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return *default_instance_;
}

SimToTracker* SimToTracker::default_instance_ = NULL;

SimToTracker* SimToTracker::New() const {
  return new SimToTracker;
}

const ::google::protobuf::Descriptor* SimToTracker::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* SimToTracker::GetReflection() const {
  if (SimToTracker_reflection_ == NULL) protobuf_BuildDesc_message_5fsim_5fto_5ftracker_2eproto();
  return SimToTracker_reflection_;
}
