// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_radio_to_tracker.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* RadioToTracker_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RadioToTracker_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  RadioToTracker_descriptor_ = file->message_type(0);
  RadioToTracker::default_instance_ = new RadioToTracker();
  static const int RadioToTracker_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioToTracker, nada_),
  };
  RadioToTracker_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RadioToTracker_descriptor_,
      RadioToTracker::default_instance_,
      RadioToTracker_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioToTracker, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioToTracker, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(RadioToTracker));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RadioToTracker_descriptor_, RadioToTracker::default_instance_);
  RadioToTracker::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\036message_radio_to_tracker.proto\"\036\n\016Radi"
    "oToTracker\022\014\n\004nada\030\001 \002(\002", 64,
  &protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fradio_5fto_5ftracker_2eproto {
  StaticDescriptorInitializer_message_5fradio_5fto_5ftracker_2eproto() {
    protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto();
  }
} static_descriptor_initializer_message_5fradio_5fto_5ftracker_2eproto_;


// ===================================================================


RadioToTracker::RadioToTracker()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    nada_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void RadioToTracker::InitAsDefaultInstance() {}

RadioToTracker::RadioToTracker(const RadioToTracker& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    nada_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

RadioToTracker::~RadioToTracker() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* RadioToTracker::descriptor() {
  if (RadioToTracker_descriptor_ == NULL) protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto();
  return RadioToTracker_descriptor_;
}

const RadioToTracker& RadioToTracker::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto();
  return *default_instance_;
}

RadioToTracker* RadioToTracker::default_instance_ = NULL;

RadioToTracker* RadioToTracker::New() const {
  return new RadioToTracker;
}

const ::google::protobuf::Descriptor* RadioToTracker::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* RadioToTracker::GetReflection() const {
  if (RadioToTracker_reflection_ == NULL) protobuf_BuildDesc_message_5fradio_5fto_5ftracker_2eproto();
  return RadioToTracker_reflection_;
}
