// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_ai_to_gui.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* GUIRobot_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GUIRobot_reflection_ = NULL;
const ::google::protobuf::Descriptor* GUIBall_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GUIBall_reflection_ = NULL;
const ::google::protobuf::Descriptor* AIToGUI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AIToGUI_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  GUIRobot_descriptor_ = file->message_type(0);
  GUIRobot::default_instance_ = new GUIRobot();
  static const int GUIRobot_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, current_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, current_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, current_theta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, future_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, future_y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, future_theta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, past_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, past_y_),
  };
  GUIRobot_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GUIRobot_descriptor_,
      GUIRobot::default_instance_,
      GUIRobot_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIRobot, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GUIRobot));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GUIRobot_descriptor_, GUIRobot::default_instance_);
  GUIBall_descriptor_ = file->message_type(1);
  GUIBall::default_instance_ = new GUIBall();
  static const int GUIBall_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIBall, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIBall, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIBall, past_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIBall, past_y_),
  };
  GUIBall_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GUIBall_descriptor_,
      GUIBall::default_instance_,
      GUIBall_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIBall, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIBall, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GUIBall));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GUIBall_descriptor_, GUIBall::default_instance_);
  AIToGUI_descriptor_ = file->message_type(2);
  AIToGUI::default_instance_ = new AIToGUI();
  static const int AIToGUI_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToGUI, blue_robots_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToGUI, yellow_robots_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToGUI, ball_),
  };
  AIToGUI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AIToGUI_descriptor_,
      AIToGUI::default_instance_,
      AIToGUI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToGUI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToGUI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(AIToGUI));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AIToGUI_descriptor_, AIToGUI::default_instance_);
  GUIRobot::default_instance_->InitAsDefaultInstance();
  GUIBall::default_instance_->InitAsDefaultInstance();
  AIToGUI::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\027message_ai_to_gui.proto\"\241\001\n\010GUIRobot\022\021"
    "\n\tcurrent_x\030\001 \002(\005\022\021\n\tcurrent_y\030\002 \002(\005\022\025\n\r"
    "current_theta\030\003 \002(\002\022\020\n\010future_x\030\004 \002(\005\022\020\n"
    "\010future_y\030\005 \002(\005\022\024\n\014future_theta\030\006 \002(\002\022\016\n"
    "\006past_x\030\007 \002(\005\022\016\n\006past_y\030\010 \002(\005\"?\n\007GUIBall"
    "\022\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005\022\016\n\006past_x\030\003 \002(\005\022\016"
    "\n\006past_y\030\004 \002(\005\"c\n\007AIToGUI\022\036\n\013blue_robots"
    "\030\001 \003(\0132\t.GUIRobot\022 \n\ryellow_robots\030\002 \003(\013"
    "2\t.GUIRobot\022\026\n\004ball\030\003 \002(\0132\010.GUIBall", 355,
  &protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fai_5fto_5fgui_2eproto {
  StaticDescriptorInitializer_message_5fai_5fto_5fgui_2eproto() {
    protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  }
} static_descriptor_initializer_message_5fai_5fto_5fgui_2eproto_;


// ===================================================================









GUIRobot::GUIRobot()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    current_x_(0),
    current_y_(0),
    current_theta_(0),
    future_x_(0),
    future_y_(0),
    future_theta_(0),
    past_x_(0),
    past_y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GUIRobot::InitAsDefaultInstance() {}

GUIRobot::GUIRobot(const GUIRobot& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    current_x_(0),
    current_y_(0),
    current_theta_(0),
    future_x_(0),
    future_y_(0),
    future_theta_(0),
    past_x_(0),
    past_y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GUIRobot::~GUIRobot() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GUIRobot::descriptor() {
  if (GUIRobot_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return GUIRobot_descriptor_;
}

const GUIRobot& GUIRobot::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return *default_instance_;
}

GUIRobot* GUIRobot::default_instance_ = NULL;

GUIRobot* GUIRobot::New() const {
  return new GUIRobot;
}

const ::google::protobuf::Descriptor* GUIRobot::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GUIRobot::GetReflection() const {
  if (GUIRobot_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return GUIRobot_reflection_;
}

// ===================================================================





GUIBall::GUIBall()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0),
    y_(0),
    past_x_(0),
    past_y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GUIBall::InitAsDefaultInstance() {}

GUIBall::GUIBall(const GUIBall& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    x_(0),
    y_(0),
    past_x_(0),
    past_y_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GUIBall::~GUIBall() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GUIBall::descriptor() {
  if (GUIBall_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return GUIBall_descriptor_;
}

const GUIBall& GUIBall::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return *default_instance_;
}

GUIBall* GUIBall::default_instance_ = NULL;

GUIBall* GUIBall::New() const {
  return new GUIBall;
}

const ::google::protobuf::Descriptor* GUIBall::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GUIBall::GetReflection() const {
  if (GUIBall_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return GUIBall_reflection_;
}

// ===================================================================




AIToGUI::AIToGUI()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    ball_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void AIToGUI::InitAsDefaultInstance() {  ball_ = const_cast< ::GUIBall*>(&::GUIBall::default_instance());
}

AIToGUI::AIToGUI(const AIToGUI& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    ball_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

AIToGUI::~AIToGUI() {
  if (this != default_instance_) {
    delete ball_;
  }
}

const ::google::protobuf::Descriptor* AIToGUI::descriptor() {
  if (AIToGUI_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return AIToGUI_descriptor_;
}

const AIToGUI& AIToGUI::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return *default_instance_;
}

AIToGUI* AIToGUI::default_instance_ = NULL;

AIToGUI* AIToGUI::New() const {
  return new AIToGUI;
}

const ::google::protobuf::Descriptor* AIToGUI::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* AIToGUI::GetReflection() const {
  if (AIToGUI_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fgui_2eproto();
  return AIToGUI_reflection_;
}
