// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_ai_to_sim.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* KickAI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  KickAI_reflection_ = NULL;
const ::google::protobuf::Descriptor* RobotAI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RobotAI_reflection_ = NULL;
const ::google::protobuf::Descriptor* AIToSim_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AIToSim_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  KickAI_descriptor_ = file->message_type(0);
  KickAI::default_instance_ = new KickAI();
  static const int KickAI_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KickAI, intensity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KickAI, is_chip_kick_),
  };
  KickAI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      KickAI_descriptor_,
      KickAI::default_instance_,
      KickAI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KickAI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KickAI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(KickAI));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    KickAI_descriptor_, KickAI::default_instance_);
  RobotAI_descriptor_ = file->message_type(1);
  RobotAI::default_instance_ = new RobotAI();
  static const int RobotAI_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, r_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, theta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, omega_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, movement_intensity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, kick_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, future_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, future_y_),
  };
  RobotAI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RobotAI_descriptor_,
      RobotAI::default_instance_,
      RobotAI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RobotAI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(RobotAI));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RobotAI_descriptor_, RobotAI::default_instance_);
  AIToSim_descriptor_ = file->message_type(2);
  AIToSim::default_instance_ = new AIToSim();
  static const int AIToSim_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToSim, robots_),
  };
  AIToSim_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AIToSim_descriptor_,
      AIToSim::default_instance_,
      AIToSim_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToSim, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToSim, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(AIToSim));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AIToSim_descriptor_, AIToSim::default_instance_);
  KickAI::default_instance_->InitAsDefaultInstance();
  RobotAI::default_instance_->InitAsDefaultInstance();
  AIToSim::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\027message_ai_to_sim.proto\"1\n\006KickAI\022\021\n\ti"
    "ntensity\030\001 \002(\r\022\024\n\014is_chip_kick\030\002 \002(\010\"\211\001\n"
    "\007RobotAI\022\t\n\001r\030\003 \002(\001\022\r\n\005theta\030\004 \002(\001\022\r\n\005om"
    "ega\030\005 \002(\001\022\032\n\022movement_intensity\030\006 \002(\001\022\025\n"
    "\004kick\030\007 \002(\0132\007.KickAI\022\020\n\010future_x\030\010 \001(\r\022\020"
    "\n\010future_y\030\t \001(\r\"#\n\007AIToSim\022\030\n\006robots\030\001 "
    "\003(\0132\010.RobotAI", 253,
  &protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fai_5fto_5fsim_2eproto {
  StaticDescriptorInitializer_message_5fai_5fto_5fsim_2eproto() {
    protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  }
} static_descriptor_initializer_message_5fai_5fto_5fsim_2eproto_;


// ===================================================================



KickAI::KickAI()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    intensity_(0u),
    is_chip_kick_(false) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void KickAI::InitAsDefaultInstance() {}

KickAI::KickAI(const KickAI& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    intensity_(0u),
    is_chip_kick_(false) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

KickAI::~KickAI() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* KickAI::descriptor() {
  if (KickAI_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return KickAI_descriptor_;
}

const KickAI& KickAI::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return *default_instance_;
}

KickAI* KickAI::default_instance_ = NULL;

KickAI* KickAI::New() const {
  return new KickAI;
}

const ::google::protobuf::Descriptor* KickAI::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* KickAI::GetReflection() const {
  if (KickAI_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return KickAI_reflection_;
}

// ===================================================================








RobotAI::RobotAI()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    r_(0),
    theta_(0),
    omega_(0),
    movement_intensity_(0),
    kick_(NULL),
    future_x_(0u),
    future_y_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void RobotAI::InitAsDefaultInstance() {  kick_ = const_cast< ::KickAI*>(&::KickAI::default_instance());
}

RobotAI::RobotAI(const RobotAI& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    r_(0),
    theta_(0),
    omega_(0),
    movement_intensity_(0),
    kick_(NULL),
    future_x_(0u),
    future_y_(0u) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

RobotAI::~RobotAI() {
  if (this != default_instance_) {
    delete kick_;
  }
}

const ::google::protobuf::Descriptor* RobotAI::descriptor() {
  if (RobotAI_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return RobotAI_descriptor_;
}

const RobotAI& RobotAI::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return *default_instance_;
}

RobotAI* RobotAI::default_instance_ = NULL;

RobotAI* RobotAI::New() const {
  return new RobotAI;
}

const ::google::protobuf::Descriptor* RobotAI::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* RobotAI::GetReflection() const {
  if (RobotAI_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return RobotAI_reflection_;
}

// ===================================================================


AIToSim::AIToSim()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void AIToSim::InitAsDefaultInstance() {}

AIToSim::AIToSim(const AIToSim& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

AIToSim::~AIToSim() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* AIToSim::descriptor() {
  if (AIToSim_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return AIToSim_descriptor_;
}

const AIToSim& AIToSim::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return *default_instance_;
}

AIToSim* AIToSim::default_instance_ = NULL;

AIToSim* AIToSim::New() const {
  return new AIToSim;
}

const ::google::protobuf::Descriptor* AIToSim::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* AIToSim::GetReflection() const {
  if (AIToSim_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fsim_2eproto();
  return AIToSim_reflection_;
}
