// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message_radio_to_tracker.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* RadioToTracker_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RadioToTracker_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_message_5fradio_5fto_5ftracker_2eproto() {
  protobuf_AddDesc_message_5fradio_5fto_5ftracker_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "message_radio_to_tracker.proto");
  GOOGLE_CHECK(file != NULL);
  RadioToTracker_descriptor_ = file->message_type(0);
  static const int RadioToTracker_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioToTracker, nada_),
  };
  RadioToTracker_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RadioToTracker_descriptor_,
      RadioToTracker::default_instance_,
      RadioToTracker_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioToTracker, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RadioToTracker, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RadioToTracker));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_message_5fradio_5fto_5ftracker_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RadioToTracker_descriptor_, &RadioToTracker::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_message_5fradio_5fto_5ftracker_2eproto() {
  delete RadioToTracker::default_instance_;
  delete RadioToTracker_reflection_;
}

void protobuf_AddDesc_message_5fradio_5fto_5ftracker_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036message_radio_to_tracker.proto\"\036\n\016Radi"
    "oToTracker\022\014\n\004nada\030\001 \002(\002", 64);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message_radio_to_tracker.proto", &protobuf_RegisterTypes);
  RadioToTracker::default_instance_ = new RadioToTracker();
  RadioToTracker::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_message_5fradio_5fto_5ftracker_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fradio_5fto_5ftracker_2eproto {
  StaticDescriptorInitializer_message_5fradio_5fto_5ftracker_2eproto() {
    protobuf_AddDesc_message_5fradio_5fto_5ftracker_2eproto();
  }
} static_descriptor_initializer_message_5fradio_5fto_5ftracker_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int RadioToTracker::kNadaFieldNumber;
#endif  // !_MSC_VER

RadioToTracker::RadioToTracker()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void RadioToTracker::InitAsDefaultInstance() {
}

RadioToTracker::RadioToTracker(const RadioToTracker& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void RadioToTracker::SharedCtor() {
  _cached_size_ = 0;
  nada_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RadioToTracker::~RadioToTracker() {
  SharedDtor();
}

void RadioToTracker::SharedDtor() {
  if (this != default_instance_) {
  }
}

void RadioToTracker::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RadioToTracker::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RadioToTracker_descriptor_;
}

const RadioToTracker& RadioToTracker::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_5fradio_5fto_5ftracker_2eproto();  return *default_instance_;
}

RadioToTracker* RadioToTracker::default_instance_ = NULL;

RadioToTracker* RadioToTracker::New() const {
  return new RadioToTracker;
}

void RadioToTracker::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    nada_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RadioToTracker::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required float nada = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &nada_)));
          _set_bit(0);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void RadioToTracker::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required float nada = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->nada(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* RadioToTracker::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required float nada = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->nada(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int RadioToTracker::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required float nada = 1;
    if (has_nada()) {
      total_size += 1 + 4;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RadioToTracker::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RadioToTracker* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RadioToTracker*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RadioToTracker::MergeFrom(const RadioToTracker& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      set_nada(from.nada());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RadioToTracker::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RadioToTracker::CopyFrom(const RadioToTracker& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RadioToTracker::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void RadioToTracker::Swap(RadioToTracker* other) {
  if (other != this) {
    std::swap(nada_, other->nada_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RadioToTracker::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RadioToTracker_descriptor_;
  metadata.reflection = RadioToTracker_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
