// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_ai_to_radio.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* AIToRadio_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AIToRadio_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  AIToRadio_descriptor_ = file->message_type(0);
  AIToRadio::default_instance_ = new AIToRadio();
  static const int AIToRadio_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToRadio, nada_),
  };
  AIToRadio_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AIToRadio_descriptor_,
      AIToRadio::default_instance_,
      AIToRadio_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToRadio, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AIToRadio, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(AIToRadio));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AIToRadio_descriptor_, AIToRadio::default_instance_);
  AIToRadio::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\031message_ai_to_radio.proto\"\031\n\tAIToRadio"
    "\022\014\n\004nada\030\001 \002(\002", 54,
  &protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fai_5fto_5fradio_2eproto {
  StaticDescriptorInitializer_message_5fai_5fto_5fradio_2eproto() {
    protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto();
  }
} static_descriptor_initializer_message_5fai_5fto_5fradio_2eproto_;


// ===================================================================


AIToRadio::AIToRadio()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    nada_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void AIToRadio::InitAsDefaultInstance() {}

AIToRadio::AIToRadio(const AIToRadio& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    nada_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

AIToRadio::~AIToRadio() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* AIToRadio::descriptor() {
  if (AIToRadio_descriptor_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto();
  return AIToRadio_descriptor_;
}

const AIToRadio& AIToRadio::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto();
  return *default_instance_;
}

AIToRadio* AIToRadio::default_instance_ = NULL;

AIToRadio* AIToRadio::New() const {
  return new AIToRadio;
}

const ::google::protobuf::Descriptor* AIToRadio::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* AIToRadio::GetReflection() const {
  if (AIToRadio_reflection_ == NULL) protobuf_BuildDesc_message_5fai_5fto_5fradio_2eproto();
  return AIToRadio_reflection_;
}
