// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "messages_robocup_ssl_refbox_log.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* Log_Frame_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Log_Frame_reflection_ = NULL;
const ::google::protobuf::Descriptor* Refbox_Log_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Refbox_Log_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  Log_Frame_descriptor_ = file->message_type(0);
  Log_Frame::default_instance_ = new Log_Frame();
  static const int Log_Frame_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, frame_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, refbox_cmd_),
  };
  Log_Frame_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Log_Frame_descriptor_,
      Log_Frame::default_instance_,
      Log_Frame_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Log_Frame, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Log_Frame));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Log_Frame_descriptor_, Log_Frame::default_instance_);
  Refbox_Log_descriptor_ = file->message_type(1);
  Refbox_Log::default_instance_ = new Refbox_Log();
  static const int Refbox_Log_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Refbox_Log, log_),
  };
  Refbox_Log_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Refbox_Log_descriptor_,
      Refbox_Log::default_instance_,
      Refbox_Log_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Refbox_Log, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Refbox_Log, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(Refbox_Log));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Refbox_Log_descriptor_, Refbox_Log::default_instance_);
  Log_Frame::default_instance_->InitAsDefaultInstance();
  Refbox_Log::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  ::protobuf_BuildDesc_messages_5frobocup_5fssl_5fdetection_2eproto();
  pool->InternalBuildGeneratedFile(
    "\n%messages_robocup_ssl_refbox_log.proto\032"
    "$messages_robocup_ssl_detection.proto\"C\n"
    "\tLog_Frame\022\"\n\005frame\030\001 \002(\0132\023.SSL_Detectio"
    "nFrame\022\022\n\nrefbox_cmd\030\002 \002(\t\"%\n\nRefbox_Log"
    "\022\027\n\003log\030\001 \003(\0132\n.Log_Frame", 185,
  &protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto {
  StaticDescriptorInitializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto() {
    protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  }
} static_descriptor_initializer_messages_5frobocup_5fssl_5frefbox_5flog_2eproto_;


// ===================================================================


const ::std::string Log_Frame::_default_refbox_cmd_;
Log_Frame::Log_Frame()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    frame_(NULL),
    refbox_cmd_(const_cast< ::std::string*>(&_default_refbox_cmd_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Log_Frame::InitAsDefaultInstance() {  frame_ = const_cast< ::SSL_DetectionFrame*>(&::SSL_DetectionFrame::default_instance());
}

Log_Frame::Log_Frame(const Log_Frame& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    frame_(NULL),
    refbox_cmd_(const_cast< ::std::string*>(&_default_refbox_cmd_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Log_Frame::~Log_Frame() {
  if (refbox_cmd_ != &_default_refbox_cmd_) {
    delete refbox_cmd_;
  }
  if (this != default_instance_) {
    delete frame_;
  }
}

const ::google::protobuf::Descriptor* Log_Frame::descriptor() {
  if (Log_Frame_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  return Log_Frame_descriptor_;
}

const Log_Frame& Log_Frame::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  return *default_instance_;
}

Log_Frame* Log_Frame::default_instance_ = NULL;

Log_Frame* Log_Frame::New() const {
  return new Log_Frame;
}

const ::google::protobuf::Descriptor* Log_Frame::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Log_Frame::GetReflection() const {
  if (Log_Frame_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  return Log_Frame_reflection_;
}

// ===================================================================


Refbox_Log::Refbox_Log()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void Refbox_Log::InitAsDefaultInstance() {}

Refbox_Log::Refbox_Log(const Refbox_Log& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

Refbox_Log::~Refbox_Log() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* Refbox_Log::descriptor() {
  if (Refbox_Log_descriptor_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  return Refbox_Log_descriptor_;
}

const Refbox_Log& Refbox_Log::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  return *default_instance_;
}

Refbox_Log* Refbox_Log::default_instance_ = NULL;

Refbox_Log* Refbox_Log::New() const {
  return new Refbox_Log;
}

const ::google::protobuf::Descriptor* Refbox_Log::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* Refbox_Log::GetReflection() const {
  if (Refbox_Log_reflection_ == NULL) protobuf_BuildDesc_messages_5frobocup_5fssl_5frefbox_5flog_2eproto();
  return Refbox_Log_reflection_;
}
