// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "message_gui_to_ai.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace {

const ::google::protobuf::Descriptor* GUIToAI_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GUIToAI_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  GUIToAI_descriptor_ = file->message_type(0);
  GUIToAI::default_instance_ = new GUIToAI();
  static const int GUIToAI_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIToAI, nada_),
  };
  GUIToAI_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GUIToAI_descriptor_,
      GUIToAI::default_instance_,
      GUIToAI_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIToAI, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GUIToAI, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(GUIToAI));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GUIToAI_descriptor_, GUIToAI::default_instance_);
  GUIToAI::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\027message_gui_to_ai.proto\"\027\n\007GUIToAI\022\014\n\004"
    "nada\030\001 \002(\002", 50,
  &protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_5fgui_5fto_5fai_2eproto {
  StaticDescriptorInitializer_message_5fgui_5fto_5fai_2eproto() {
    protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto();
  }
} static_descriptor_initializer_message_5fgui_5fto_5fai_2eproto_;


// ===================================================================


GUIToAI::GUIToAI()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    nada_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void GUIToAI::InitAsDefaultInstance() {}

GUIToAI::GUIToAI(const GUIToAI& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    nada_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

GUIToAI::~GUIToAI() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* GUIToAI::descriptor() {
  if (GUIToAI_descriptor_ == NULL) protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto();
  return GUIToAI_descriptor_;
}

const GUIToAI& GUIToAI::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto();
  return *default_instance_;
}

GUIToAI* GUIToAI::default_instance_ = NULL;

GUIToAI* GUIToAI::New() const {
  return new GUIToAI;
}

const ::google::protobuf::Descriptor* GUIToAI::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* GUIToAI::GetReflection() const {
  if (GUIToAI_reflection_ == NULL) protobuf_BuildDesc_message_5fgui_5fto_5fai_2eproto();
  return GUIToAI_reflection_;
}
